### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sisensee** [Maker-Management-Platform/docs#16]
Unraid docker/app template. Much easier to install via docker app integration.

**Comment by EduardoOliveira** [comment]
Hi, not an unraid user, and from what I've seen you need an instance to generate the manifest.
I'm more than happy to help out, and host the manifest file if someone does the process in their instance.

**Comment by sisensee** [comment]
Never tried or even read docs on it but I will gladly help out!

**Comment by iotemylabs** [comment]
I currently use MMP on multiple Unraid servers myself, and the best success I had was using an application like [Dockge](https://github.com/louislam/dockge) to do a compose file: 
```yaml
version: "3.6"
services:
  agent:
    image: ghcr.io/maker-management-platform/agent:latest
    container_name: agent
    volumes:
      - /mnt/user/appdata/mmp/library:/library # should contain your project library
      - /mnt/user/appdata/mmp/data:/data # will contain config and state files
    ports:
      - 8000:8000
    restart: unless-stopped
  ui:
    image: ghcr.io/maker-management-platform/mmp-ui:latest
    container_name: ui
    ports:
      - 8081:8081
    environment:
      - AGENT_ADDRESS=agent:8000
    restart: unless-stopped
```
It's been working reliably for me for organizing 3D Prints so far.
